name = "MyFirstPackage"
uuid = "42b9b681-6bba-4c36-98b9-7240a4f8926f"
authors = ["zhaohui zhi"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
